### ISSUE TITLE
Using pym with a webapp that already uses parameters(and filters) in the child URL.

### ISSUE THREAD

**Issue by danieloostra** [nprapps/pym.js#104]
I'm trying to embed a web app that puts arguments in the url of the child page similarly to how pym.js does, it also filters them...  What happens is when it renders on the parent page the app (java) fails because of the extra parameters in the url of the child page when it's called. The error page embeds superbly.

In other words when the child page renders on the parent page the "new" url doesn't work. (http://example.com/BASE_URL_FOR_APP**?initialWidth=903&childId=pym…**) 

Is there an established workaround already created about this? Is there a way to have the parent page render with the original child page url without the extra args?

Thanks ahead all.

**Comment by coreyhaines** [comment]
Hi, @danieloostra 
For this, do you mean that it ends up something like
`http://example.com/path1/path2/file.html?foo=bar?initialWidth=903....`
So, it is adding them on in a bad way. Or is it just the fact that there are extra parameters at all. Or is it removing the other ones?
Could you give a couple concrete examples of original url and url after pym munges it?

If the app is failing because there are extra parameters at all, that is a tough thing to solve, as the pym child needs to have those, and the url is the standard way to pass them. Hopefully that isn't the case, and it is just that pym is not adding them appropriately.

**Comment by eads** [comment]
Agree with Corey that this is a tough thing to solve if the app is failing due to the extra parameters. We could look into other ways to pass those into the child but the current method is a reasonable way to do it and possibly the most reasonable way.

**Comment by coreyhaines** [comment]
I'm still hoping to get a concrete example from @danieloostra as I'm not sure I totally understand.

**Comment by jjelosua** [comment]
@danieloostra can you provide an simple example of the bug. I agree with @coreyhaines and @eads that if the problem you are facing is due to extra parameters being added to the url it is a though thing to solve since it seems to be the standard way to pass attributes to the child. I am closing the issue for now but please reopen it if you can provide us with an example of the bug you are facing.
