### ISSUE TITLE
Some hosts appear to block the `?parentUrl=` parameter for embedded pages.

### ISSUE THREAD

**Issue by benlk** [nprapps/pym.js#120]
This ticket is a copy of [this tweet thread](https://twitter.com/benlkeith/status/727255993743249408), with added details.
## The setting

A few days ago, I was using http://f.benlk.com/inn/ie/slidertest5.html as the child in a Pym embed created using https://github.com/INN/pym-shortcode:

``` html
<div id="pym_0"></div>
<script src="http://insideenergy.vagrant.dev/wp-content/plugins/pym-shortcode/js/pym.js"></script>
<script>var pym_0 = new pym.Parent('pym_0', 'http://f.benlk.com/inn/ie/slidertest5.html', {})</script>
```

The version of pym.js in question is from a41b140, the current master version of this repository, plus a shim method [`sendHeightToParent`](https://github.com/INN/pym-shortcode/blob/master/js/pym.js#L525-L531) for compatibility with an existing [Largo](https://github.com/INN/Largo) child theme's use of pym.js

The url generated by modern Pym for the child page on initial load is http://f.benlk.com/inn/ie/slidertest5.html?initialWidth=760&childId=pym_0&parentUrl=http%3A%2F%2Finsideenergy.vagrant.dev%2F2016%2F05%2F02%2Fpym-testing-post%2F
## The problem

When using the most-recent version of Pym, the embedded page returned a 403 Forbidden error.

When using [an older version of Pym](https://bitbucket.org/projectlargo/theme-insideenergy/src/3de3e0127ab3b118d8fb5200f021e2e4a802819e/js/pym.js?fileviewer=file-view-default) dating to approximately July 7, 2014, the embedded page did not return a 403.

Examination of the loaded page revealed that the newer version of Pym was setting a `parentUrl` parameter in the query string, and that the presence of this parameter was causing a 403.
## Reproduction

Here are the URLs I tried, with their status:

| status | URL |
| :-- | :-- |
| 200 | http://f.benlk.com/inn/ie/slidertest5.html |
| 200 | http://f.benlk.com/inn/ie/slidertest5.html?initialWidth=760&childId=pym_0 |
| 403 | http://f.benlk.com/inn/ie/slidertest5.html?initialWidth=760&childId=pym_0&parentUrl=http%3A%2F%2Finsideenergy.vagrant.dev%2F2016%2F05%2F02%2Fpym-testing-post%2F |
| 403 | http://f.benlk.com/inn/ie/slidertest5.html?initialWidth=760&childId=pym_0&parentUrl |
| 403 | http://f.benlk.com/inn/ie/slidertest5.html?parentUrl |
| 403 | http://f.benlk.com/inn/?parentUrl |
| 200 | http://benlk.com/?parentUrl |

http://benlk.com/ has [a `.htaccess` file with many rewrite rules](https://github.com/Circa75/dropplets/blob/29bb3e9451d1a3fe8829fd171d3edf9fc2173629/dropplets/save.php#L102-L112); http://f.benlk.com/inn/ does not have any `.htaccess` file.
## Resolution

I contacted my host and they removed _something_ that was causing the 403.

![chjqm0vweae0uhr](https://cloud.githubusercontent.com/assets/1754187/15000989/d55b392c-1161-11e6-8fe9-be9491858cdc.jpg)

Here's the relevant part of the chat transcript:

> I replicated your error
> I pulled the live-error log on this 403 to figure out what the cause was
> and you're hitting a mod_security rule ID set in place by our servers for security purposes
> It's not clear which one, so I need to continue investigating. I appreciate your patience!
> Figured it out
> I can whitelist it for you
> One moment please
> [*] Configuration good! Restarting Apache ... Done!

To recap: There was a host-specific rule being enforced by Apache's `mod_security` that was causing pages with a `parentUrl` parameter in the query to be 403'd. And it didn't apply in directories with a `.htaccess` affecting rewrite rules.

A quick googling didn't find anything about mod_rewrite and `parentUrl`, so I have no idea what the rule causing this was. Hostgator's customer-facing documentation does not say anything about that parameter in specific. Here's [what the official docs have to say about mod_security](https://support.hostgator.com/articles/specialized-help/403-forbidden-or-no-permission-to-access).

I don't have access to the error log that the chat technician mentioned, and the logs I do have access to don't show any data from this month. 😞 
## Potential fixes

@eads suggests [making that parameter configurable](https://twitter.com/eads/status/727589066938712064).

**Comment by AlainVagner** [comment]
Hi, I encountered the same problem here.
In our CMS we have a preview system for articles based on iframes. Inside an article, I have a responsive iframe with pym.js.  The problem is that the article preview iframe is loaded through data URI (I don't know why it is done like this but I have no control on this part of the code) and the data URI is very long.

When pym.js tries to load the iframe, it passes the parentUrl parameter with the data URL in it. It is then refused by the webserver because the URL is too long (more than 4096 bytes).

Could it be possible to configure pym.js not to pass the parentUrl parameter in such a case? Or can we add a check inside pym.js to avoid passing the parentUrl parameter when longer than a fixed threshold?

**Comment by eads** [comment]
@jjelosua something for after the election.

I continue to think this could be a configuration option -- maybe something that uses `false` to disable and/or a string to override.

**Comment by AlainVagner** [comment]
@eads @jjelosua ok then, I will send you a pull request.

**Comment by jjelosua** [comment]
I would prefer a string to override with an empty string used to disable the parentUrl completely.

**Comment by eads** [comment]
That works too -- some kind of false-y value to disable and a string override.

**Comment by AlainVagner** [comment]
does this PR meet your expectations?

**Comment by jjelosua** [comment]
@AlainVagner @benlk @eads First of all sorry for all the silence....I am taking a look at the current issues and PRs and plan on releasing a 1.2.0 version soon (by middle march). I think we are somehow mixing two problems on the same issue. Please correct me if I am wrong.

* @benlk problem was the `parentUrl` query string param name itself. we can and will make this name configurable so that it can be changed if it  conflicts with security rules on some hosting servers.
* @AlainVagner problem was a matter of length of the Url, so we also need a way to `disable/override` including the parent url param however is it called in custom configurations.

Your PR @AlainVagner handles the second problem but not the first since the parentUrl will be set on the url and that would generate a `403`  in the initial configuration @benlk had.

I will actively work on a solution that handles both issues and release it soon. Again sorry for the long silence and thanks for helping us make Pym.js more resilient and flexible.

**Comment by AlainVagner** [comment]
@jjelosua no problem! You are right, we have two problems here. To you want me to open a separate issue? 
Anyway, thanks for the feedback and for your job on this awesome project :)

**Comment by jjelosua** [comment]
If you could do that it would be great...thanks for the feedback and for helping us improve the project.

I am going to create a PR for all of you to review and comment out....should be out there soon.

**Comment by AlainVagner** [comment]
done!
