### ISSUE TITLE
settings unavailable in auto-initialization

### ISSUE THREAD

**Issue by AlainVagner** [nprapps/pym.js#130]
Some settings are not available when doing an auto-initialization, for example allowfullscreen and title.
Don't you think it could be useful to have access to these settings through data attributes, like for data-pym-xdomain?

**Comment by jjelosua** [comment]
Hi @AlainVagner The auto-initialization is meant for simpler scenarios and by design they allow less complex scenarios than a manual initialization does. Can't you use a manual initialization if you need to add a more complex configuration? We want to keep the autoinit as simple as possible.

**Comment by AlainVagner** [comment]
Hi @jjelosua I have a quite simple scenario when I would like to embed an iframe containing a video player. I have no way to set up the allowfullscreen attribute on the iframe to allow the video player to go fullscreen.
Moreover we are using require.js so in my case, if I understand well, the use of pym-loader.js is mandatory. With pym-loader.js, is there any mean to access the pymParent object?
Thanks for your help!

**Comment by eads** [comment]
Did allowFullScreen not make it into the latest release? 

One question though: does the aspect ratio of the video change across viewport sizes? If so, [FitVids](http://fitvidsjs.com/) or a pure CSS approach could be better than the weight of pym.

**Comment by jjelosua** [comment]
@eads allowFullScreen did make it on the last release but not when using the simpler autoinit version, but there are many options available through manual instantiation that are not available through autoinit .

From the docs:
"Certain CMSes prevent custom Javascript from being embedded on the page. In order to allow pym to support those environments, it can be initialized via data- attributes. This limits usage of pym to simple cases, but should still be enough for many users."

It will be difficult to keep growing the number of data attributes on autoinit when new config options become available so I am reluctant to go over that road.

@AlainVagner you can access autoinited parents once loaded through `pym.autoInitInstances`

**Comment by AlainVagner** [comment]
@eads Yes the aspect ratio changes because it is a video player with a playlist.

@jjelosua I understand your concern. But perhaps data attributes are not the only way to configure autoinit. Thanks for the info about the pym.autoInitInstances, I will try to use it.

**Comment by eads** [comment]
@AlainVagner gotcha, just curious!

@jjelosua @AlainVagner I don't see what's wrong with going crazy with data attributes. Bootstrap does that and it works pretty well for a lot of people.

**Comment by AlainVagner** [comment]
@eads To my mind, the problem is not for the users of the library: documenting this list of data attributes is not a big deal. But it seems that it will increase the complexity of the code (maintaining two lists of attributes in different places, syncing them, checking the types, etc.) Another option could be to be able to pass to auto-initialization an object similar to those given to the normal initialization process. For example:
`<p data-pym-src="child.html" id="child">Loading...</p>
<script> 
    document.getElementById('child').config = { 'title': 'title', 'name': 'name'} ;
</script>
<script type="text/javascript" src="//pym.nprapps.org/pym-loader.v1.min.js"></script>` 
and perhaps  setting it as a global variable could help setting the same parameters to all pym instances in the page. In this way we avoid duplicating code to manage settings. What is your opinion @jjelosua ?

**Comment by eads** [comment]
I don't know that it's that onerous to sync data attributes with configuration settings assuming they are always exactly the same. So if your options object has 'allow-full-screen' and your data attribute is `allow-full-screen`, then it's significantly less crazy to code or document.

**Comment by AlainVagner** [comment]
@eads ok, this is what I propose in the request #131

**Comment by jjelosua** [comment]
@AlainVagner since there are different config params for Parent and Child, I do not think moving the settings to a global var would be the best approach.

@eads normally a data attribute will start with [data-*](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes)  so at least we need a bit of parsing...it is not _crazy_ obviously and doable but I wonder why not use the manual instantiation in this case @AlainVagner, because of the requirejs loading...probably right? I might as well have answered myself.

**Comment by AlainVagner** [comment]
@jjelosua yes we are currently using requirejs and we do not foresee to switch to another system anytime soon.

I agree for Parent and Child that have different configurations, but does it happen often to have parents and children in the same dom tree?

**Comment by AlainVagner** [comment]
I finally managed to load pym.js with require.js. It was not clear for me in the documentation that this was possible without pym-loader. If I remember well, this was not working with previous versions of pym.js.

**Comment by jjelosua** [comment]
@AlainVagner it is possible to load pym with require.js without the pym-loader, it is just not that easy to configure and that's why we have created the loader to simplify things and also because some CMSes strip out inline script tags. 
Be careful how you load it though are you using require.js dependencies to do that?

**Comment by AlainVagner** [comment]
@jjelosua In fact I read the code of pym-loader and tried to replicate it in our require.js configuration. It seems to work so far.

**Comment by jjelosua** [comment]
@AlainVagner we have just pushed [v1.1.0](https://github.com/nprapps/pym.js/releases/tag/v1.1.0) with esentially your pull request code but taking into account the possibility of having an empty `data-pym-allowfullcreen` to enable full screen.

**Comment by AlainVagner** [comment]
Excellent, thanks @jjelosua !
