### ISSUE TITLE
Iframe lazy loading

### ISSUE THREAD

**Issue by AlainVagner** [nprapps/pym.js#144]
We have put some pym.js auto-initialized iframes on the homepage of our news website. This works well but we would like to lazy load them to avoid loading iframes that are not displayed.
Do you think this could be an option of pym? Or it could be done like an extension or a plugin?

**Comment by bhaskarvk** [comment]
@AlainVagner Check out my fork https://github.com/bhaskarvk/pym.js. I added option to lazy load the child using https://github.com/dinbror/blazy. 
I added an option in Parent called `lazyload` which if true returns `<iframe data-src='child.html...' class='b-lazy' ...>` instead of the default `<iframe src='child.html...' ...>`. You will also need to include the bLzay javascript and initialize bLazy as described in the bLazy documentation.
