### ISSUE TITLE
leverage browser caching on cdn / Pagespeed

### ISSUE THREAD

**Issue by AlainVagner** [nprapps/pym.js#149]
We are loading pym.js from the cdn and Google Pagespeed Insights is complaining about a missing header. It seems that the expiration is not specified.

Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
https://pym.nprapps.org/pym.v1.min.js (expiration not specified)

Perhaps adding the Cache-Control: max-age header could help here?

**Comment by jjelosua** [comment]
@AlainVagner Hi Alain, thanks for pointing this out...I will try to work on a better deployment method to add Cache-Control and compression headers to the next release. Did you take a look at the v1.2.0 PR? Cheers

**Comment by eads** [comment]
@jjelosua can you check the cloudfront config? I thought it's supposed to be putting in those headers all by itself...

**Comment by AlainVagner** [comment]
@jjelosua  ok thanks! I will test the 1.2.0 PR this week in our environment. I will tell you if I see some issues.

**Comment by jjelosua** [comment]
@AlainVagner My idea is to merge it tomorrow....I tried my best to keep it backwards compatible so it should be good on your end....but let me know otherwise

**Comment by AlainVagner** [comment]
@jjelosua ok, I will test it tomorrow morning (gmt+1 here) so you will have the results on time :)

**Comment by jjelosua** [comment]
GMT+1 here too at the moment but I need to write some docs so it should be fine as long as it is before noon :)

**Comment by AlainVagner** [comment]
@jjelosua I tested, it is ok for us, thanks for your work and good luck for the release!

**Comment by jjelosua** [comment]
@AlainVagner v1.2.0 is out I have added compression and cache-control headers to the files on the CDN  your issues with PageSpeed should be solved, I am finding what I think is a weird cache issue with https://pym.nprapps.org/pym.v1.min.js could you test out on your end and tell me is you still see the Leverage browser caching issue? Thanks

**Comment by AlainVagner** [comment]
@jjelosua pym.js still appear in those warnings from Google Page Speed Insights.
This time, here is the message I get:
https://pym.nprapps.org/pym.v1.min.js (60 minutes)

According to their documentation, they recommend caching at least for 1 week and use url fingerprinting:
https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

**Comment by jjelosua** [comment]
If you use a browser to go to https://pym.nprapps.org/pym.v1.min.js and check the headers you'll see that the Cache-Control is set up at a week: 

![screenshot 2017-03-08 17 11 17](https://cloud.githubusercontent.com/assets/1834051/23712153/4dd8fe3a-0422-11e7-9c41-82664cffce93.png)


Also https://pym.nprapps.org/p.v1.m.js an alias configured exactly the same way as pym.v1.min.js does not raise the issue.
So I believe it is a temporary issue with Google Page Speed page that will be solved soon.

By mistake I have tried to enter their own page and...jajaja it does not pass the test also due to analytics.js.

**Comment by AlainVagner** [comment]
@jjelosua If I check here for https://pym.nprapps.org/pym.v1.min.js I got cache-control:max-age=3600 Perhaps your change will take some time to be propagated? Also it is a shame that analytics.js is not properly cached.

**Comment by jjelosua** [comment]
Yeah, If it happens to you tomorrow let me know and I will invalidate pym in our CDN to force a refresh...anyhow the cache-control header is there...the value of it should not be seen as an error in my opinion... so not to worried about it anyhow

**Comment by jjelosua** [comment]
@AlainVagner After carefully thinking about our use case I am going to setup max-age to one day. If we followed recommendations for Google Page Speed Insights I would set a max-age for pym source JS files of one week, but now I am reconsidering that maybe we should lower that to 1 day…since we will not be able to update the url without a big impact on our various users, if we find a bug we would need to reuse the same url and those with the file cached on their browser will need to wait a week to see the results and that can lead to a nightmare scenario. So Having a max-age of a day combined with ETag validation will lead to our optimal scenario for pym with the above mentioned circumstances. If the file has not changed the only exchange will be for ETag validation and I think we can afford that seeing the advantages of a short timestamp for bug fixing. I am going to close this issue then.

**Comment by AlainVagner** [comment]
Ok perfect, thanks !
