### ISSUE TITLE
sendHeight not resizing child page

### ISSUE THREAD

**Issue by starklmc** [nprapps/pym.js#154]
Using on the child page:

`	<script type="text/javascript">
        var pymChild = new pym.Child();
        pymChild.sendHeight();
    </script>`

The sendHeight is not returning the page height of the child page after the filter has been selected and the user clicks "search."

Sample:  https://ymcanwnc.org/schedules-2/

Thoughts?

**Comment by LuisSevillano** [comment]
Hi,
I got similar issue but to me it happens two things :
When the object starts it doesn't return the child height and neither works the event sendHeight() that I use for making a responsive chart. Any idea?

Many thanks

**Comment by jjelosua** [comment]
Hi @starklmc, Let me try to understand, trying to take a look at your sample page if looks like if the pym child looses the reference to the parent id and that will cause the messaging to the parent not to work.

The sample is a bit complicated to follow through since there are many parts involved, could you produce a sample page just with the interaction with pym so that I can take a look at?

**Comment by jjelosua** [comment]
Hi @LuisSevillano, I would ask the same if you can generate a simplified page that I can take a look at it that would help me understand what the issue you are facing is....Take a look at the docs there are some examples there to get you started...we are using pym continuously to resize graphics at NPR so that's covered by pym.js for sure. are you using the renderCallback function? is your data dynamic? 

<img width="732" alt="screenshot 2017-06-09 17 31 48" src="https://user-images.githubusercontent.com/1834051/26995259-a617d00c-4d39-11e7-8c72-28142c02cc01.png">

**Comment by LuisSevillano** [comment]
@jjelosua thank you very much for your quick response. I've already solve my problem. 
A css `position`: `absolute` attribute of two containers were causing some troubles not allowing pym to calculate the size of the child element.

Many thanks from Madrid!

Luis

**Comment by harshalone** [comment]
The only workaround or hack I found is
create a hidden button with class update_height and add an event on click sendHeight because no matter what you do renderCallback does not work. Used it on my embed page here : [Sample Page](https://www.bylde.com/events/embed/ev5ca64a1b87a8d)
```

<script>
    	
			function update_height(e) { 
			    pymChild.sendHeight();
			}
			
			$('.update_height').on('click', update_height);
			
			var pymChild = new pym.Child();
			
			setTimeout(update_height, 500);
    	
    </script>
```
