### ISSUE TITLE
pymChild.sendHeight() stop to work when loading a new page inside iframe

### ISSUE THREAD

**Issue by italo1983** [nprapps/pym.js#155]
Hi,
i've this code inside two pages:
function initEmbed() {
  var pymChild = new pym.Child({id: "catalog-widget"});
  $(window).load(function() {      
      pymChild.sendHeight();
  });
}
On first page it work correctly but when the user navigate to the second page, from the iframe , parent page does not receive the sendHeight message, i've also tried the sendMessage function but seems that communication between parent and child is broken.

**Comment by jjelosua** [comment]
Hi @italo1983, that is weird, there's an example on our blog that does exactly what you are looking for, so there must be something going other than pym.js preventing the resizing to work. Do you have a simple example that we can take a look at?

<img width="748" alt="screenshot 2017-06-22 09 56 02" src="https://user-images.githubusercontent.com/1834051/27437757-40365eaa-5731-11e7-92a6-47cef57dae01.png">

Just making sure, the parent container id has also the 'catalog-widget' id? I suppose so since the first page works correctly...as said an example will help us try to help you figure out your problem.

Cheers

**Comment by italo1983** [comment]
The problem was on the parent container id... my fault!

Thank you for your support.


Il 22/06/17 15:59, Juan Elosua ha scritto:

**Comment by jjelosua** [comment]
Glad it worked out.
