### ISSUE TITLE
Use JSON to pass messages instead of plaintext?

### ISSUE THREAD

**Issue by al-the-x** [nprapps/pym.js#43]
In attempting to utilize Pym with another library, I encountered a situation in which the other library was listening to `message` events, expecting JSON, and blindly passing the message through `JSON.parse()`. This 3rd-party would be better served by filtering messages from domains that it cared about instead of everybody and their `siblings`, and I've filed a bug with that author appropriately.

However, it made me aware of the message format that Pym was using for communication: `responsive(parent|child) [id] [height]`. Have you considered using JSON instead? This would have the advantage of utilizing [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) instead of regex parsing and make the communication a little more readable. Just a thought, and I'm happy to send a PR.

**Comment by hampelm** [comment]
At this point, this may be better handled by the message producers and consumers. However, I did want to ask about point (b) adding a json parser since this came up in some debugging today. Would the built-in `JSON.parse` not be sufficient? [caniuse suggests](http://caniuse.com/#feat=json) it's supported in IE 9.
