### ISSUE TITLE
When first element inside iframe has margin-top in throws off the height calculation

### ISSUE THREAD

**Issue by onyxfish** [nprapps/pym.js#83]
Ugh

**Comment by kAlvaro** [comment]
The same happens when you build a barebone example to test the script with no styling at all—I guess it's the same issue.

Apparently, you need to "fix" the browser default styles and e.g. add non-zero padding to `<body>`.

**Comment by TylerFisher** [comment]
Seen further reports of this. An added wrinkle: if you use polling, the height progressively changes by a factor of the margin on the element.. or something.

**Comment by jdhancock88** [comment]
Regarding @TylerFisher's comment, the height progressively changes by the combined top and bottom margin of the first element.

**Comment by NathanLawrence** [comment]
Howdy there! This is still happening to me and it is driving me batty!

**Comment by bryancasler** [comment]
My stopgap solution was to add this on Child pages.

`    
    
    <div style="height: 0px !important; width: 0px !important;">&nbsp;</div>`

**Comment by tvanantwerp** [comment]
Don't know why this issue was closed without comment. It happened to me just today and I wasted far too much time figuring out what happened. It would be an easy fix, too.

[Here is the offending line.](https://github.com/nprapps/pym.js/blob/master/src/pym.js#L941)
```javascript
var height = document.getElementsByTagName('body')[0].offsetHeight.toString();
```

Just change `body` to `html` and it's fixed.

Seems I'm not the first to notice, either, [as there's an open PR to fix it](https://github.com/nprapps/pym.js/pull/153).

**Comment by thomaswilburn** [comment]
I closed a number of issues as triage if they didn't seem active. Nothing personal. I'm evaluating the PR you indicated, and will see if I think it's safe to merge, given Pym's extremely widespread usage.

**Comment by tvanantwerp** [comment]
Thanks for taking a look @thomaswilburn--I appreciate it!

And I understand the need to make sure a change doesn't break anything else for people already using the library. I'm curious if @nprapps has considered using the full semantic version for filenames on CDN hosting. I notice it's currently available as `pym.v1.min.js` instead of the more descriptive `pym.v1.3.2.min.js`. Could help prevent inadvertently breaking things for outside users with smaller version changes if they get pegged to a specific release.

**Comment by thomaswilburn** [comment]
That's a good idea, and if we do cut a new release, I'll keep it in mind.
