### ISSUE TITLE
How to jump to top of parent page without breaking back button?

### ISSUE THREAD

**Issue by jdahdah** [nprapps/pym.js#91]
I have an external app running in an iframe that goes through several pages. It’s working nicely with the help of `var pymChild = new pym.Child({id: "app-id"});` on the child page. The only problem, however, is that due to the nature of iframes, the browser doesn’t jump back to the top of the parent page every time a new child page is loaded, which is a confusing user experience. Ideally, a user shouldn’t even notice they’re dealing with a iframe and loading a new child page should behave exactly like loading a new page.

I’ve tried `pymChild.scrollParentTo('#');`, which sort of works, but breaks the browser’s back button. What would be the best way to implement this with pym.js while preserving history? I don't need the URL to update (e.g. `history.pushState` or something), I just need it to remain unchanged. I suppose it has something to do with `sendMessage` and `window.scroll();`, but I have no clue how to combine the two. As you can tell, I'm still struggling with Javascript, so I'd be grateful for any advice you could share.

**Comment by onyxfish** [comment]
Hey Jerome, you're on the right track. You'd want to have the child ``sendMessage`` to the parent and then have the parent respond to that message by scrolling the window to the top. (If you're using jQuery you can use [scrollTop](https://api.jquery.com/scrollTop/).) Since your iframe is actually reloading you also may need to implement delay in order to ensure the message is sent before the reload occurs. You can look at the [events](https://github.com/nprapps/pym.js/tree/master/examples/events) example for a simple example of passing messages from child to parent.

Hope that helps!
