### ISSUE TITLE
Initializes inline, rather than on document ready

### ISSUE THREAD

**Issue by coreyhaines** [nprapps/pym.js#95]
We ran into this issue when pym was included in the head of the document. Because the pym script auto-initializes at load time, not document ready, it doesn't see the div tags that have a data-pym-src attribute. We have to tell our clients to put the script include at the bottom of the page. This isn't always feasible.
Would it be possible to have the initialization run at document load, so we have all the divs that mark an iframe ready?

**Comment by miohtama** [comment]
Or even better.... do not do implicit initialization at all. It should be always the responsibility of host JS application to call the library init.

**Comment by onyxfish** [comment]
@coreyhaines This is an interesting problem. It's a bit of a catch-22. We use onload because it will guarantee that inline images have loaded before it fires, which affects the height computation in the child frame if you're not using dynamic rendering. But I also understand that it creates an issue with pages where you may not control the placement of the javascript include. I'm open to suggestions about how to resolve the conflict.

@miohtama Implicit initialization is a requirement for many users who are not able to add custom javascript blocks through their CMS.

**Comment by coreyhaines** [comment]
@miohtama Some of our customers use Core Publisher, which strips out the javascript. :) Plus, I prefer the auto-initialization based on data attributes.

**Comment by coreyhaines** [comment]
@onyxfish I haven't looked into the code totally deeply, but it appears this
https://github.com/nprapps/pym.js/blob/master/src/pym.js#L14
is the cause of my issue. As soon as the script loads, the factory gets executed, which has a raw call to `_autoInit()`
https://github.com/nprapps/pym.js/blob/master/src/pym.js#L582

This means that the script tag has to be located AFTER the marker div.

Perhaps wrapping the call to `_autoInit()` to execute on the DOMContentLoaded event? Admittedly I don't know all the use cases you had, but was there a reason to have it execute immediately?

**Comment by onyxfish** [comment]
Huh, I thought that was wrapped in an onload handler... okay, this may be fixable without screwing up anything else. I'll take a closer look.

**Comment by coreyhaines** [comment]
Let me know if I can help. I may be missing where it is wrapped, but I don't think so. Also, the behavior seems to indicate it isn't.

Thanks.

**Comment by coreyhaines** [comment]
Have resolved this in my fork. Outlined in this PR: https://github.com/nprapps/pym.js/pull/105
